### ISSUE TITLE
Create a DO droplet backup job

### ISSUE THREAD

**Issue by katefike** [katefike/sage#123]
![image](https://github.com/katefike/sage/assets/81718723/d8b1e6d2-6d9e-44ad-9314-8eb70e2a66db)

The backups are from 12AM - 4AM UTC
Emails are parsed at 12PM UTC
```
    - name: Create a cron job for parsing transactions from emails
      ansible.builtin.cron:
        name: Parse transactions from emails
        weekday: '*'
        minute: '0'
        hour: '12'
```
